easy_admin:
    entities:
        Users:
            class: User\Document\User

            controller: Admin\CustomController\AdminUserController

            disabled_actions:
                - edit
                - delete

            list:
                actions:
                    - show

                fields:
                    - id
                    - username
                    - email
                    - roles
                    - { property: emailConfirmed, type: boolean }
                    - createdAt

            show:
                fields:
                    - id
                    - username
                    - email
                    - roles
                    - emailConfirmed
                    - ululeUsername
                    - createdAt
                    - updatedAt

            new:
                fields:
                    - username
                    - email
                    - property: plainPassword
                      type: password
                      type_options:
                          help: admin.entities.users.password_help
