easy_admin:
    site_name: Studio Agate

    list:
        max_results: 50

    design:
        brand_color: 'rgb(88, 88, 216)'

        templates:
            layout: easy_admin/layout.html.twig

        form_theme:
            - 'form/easyadmin_form_theme.html.twig'

        menu:
            - { label: 'admin.links.admin_home', route: 'easyadmin', default: true, icon: 'home' }
            - { label: 'admin.links.back_to_site', route: 'corahn_rin_home', icon: 'arrow-left' }

            - { label: 'admin.menu.users', permission: ROLE_ADMIN }
            - { entity: 'Users', icon: 'users', permission: ROLE_ADMIN }

            - { label: 'admin.menu.corahn_rin', permission: ROLE_ADMIN }
            - { label: 'admin.menu.corahn_rin.ogham', entity: Ogham, permission: ROLE_ADMIN }
            - { label: 'admin.menu.corahn_rin.import_character', route: 'admin_legacy_characters', icon: file-import, permission: ROLE_ADMIN }
