doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver: pdo_mysql
                server_version: 5.7
                url: '%env(DATABASE_URL)%'
                charset: utf8
                profiling_collect_backtrace: '%kernel.debug%'
                default_table_options:
                    charset: utf8
                    collate: utf8_unicode_ci
            legacy:
                driver: pdo_mysql
                server_version: 5.7
                url: '%env(DATABASE_URL_LEGACY)%'
                charset: utf8
                logging: false
                profiling: false