doctrine:
    dbal:
        default_connection: default
        types:
            zone_id: EsterenMaps\Id\ZoneIdType
        connections:
            default:
                driver: pdo_mysql
                server_version: 5.7
                url: '%env(DATABASE_URL)%'
                charset: utf8
                profiling_collect_backtrace: '%kernel.debug%'
                default_table_options:
                    charset: utf8
                    collate: utf8_unicode_ci
            legacy:
                driver: pdo_mysql
                server_version: 5.7
                url: '%env(DATABASE_URL_LEGACY)%'
                charset: utf8
                logging: false
                profiling: false
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            CorahnRin:
                type: annotation
                dir: '%kernel.project_dir%/src/CorahnRin/Entity/'
                is_bundle: false
                prefix: CorahnRin\Entity
                alias: CorahnRin
            User:
                type: annotation
                dir: '%kernel.project_dir%/src/User/Entity/'
                is_bundle: false
                prefix: User\Entity
                alias: User
