doctrine_mongodb:
    auto_generate_proxy_classes: true
    auto_generate_hydrator_classes: true
    connections:
        default:
            server: '%env(resolve:MONGODB_URL)%'
            options: {}
    types:
        zone_id: EsterenMaps\Id\ZoneIdType
    default_database: '%env(resolve:MONGODB_DB)%'
    default_document_manager: default
    document_managers:
        default:
            auto_mapping: true
            mappings:
                CorahnRin:
                    type: annotation
                    dir: '%kernel.project_dir%/src/CorahnRin/Document/'
                    is_bundle: false
                    prefix: CorahnRin\Document
                    alias: CorahnRin
                User:
                    type: annotation
                    dir: '%kernel.project_dir%/src/User/Document/'
                    is_bundle: false
                    prefix: User\Document
                    alias: User
