version: '3'

volumes:
    node_modules:
    db_data:
    mongo_data:

services:

    php:
        build:
            dockerfile: ./docker/php/Dockerfile
            context: .
        working_dir: /srv/
        volumes:
            - ./:/srv
        links:
            - database
            - mailer

    mailer:
        build: ./docker/mailcatcher/

    node:
        build: ./docker/node/
        working_dir: /srv/
        volumes:
            - ./:/srv
        command: 'sleep 99999d'

    mongodb:
        image: 'mongo:3.7'
        working_dir: /srv/
        volumes:
            - mongo_data:/data/db

    database:
        image: 'mysql:5.7'
        working_dir: /srv/
        volumes:
            # Dump can be saved in the "data/" directory if you need.
            - ./data/:/srv/:ro
            - ./docker/mysql/etc/bind.cnf:/etc/mysql/conf.d/bind.cnf
            - ./docker/mysql/etc/docker-override.cnf:/etc/mysql/conf.d/docker.cnf
            - db_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_HOST: 0.0.0.0
            MYSQL_ROOT_HOST: "%"
