version: '3'

volumes:
    node_modules:
    db_data:

services:

    php:
        # Docker build here:
        # https://hub.docker.com/r/pierstoval/studio-agate-portal/
        # https://github.com/StudioAgate/DockerPortalApp
        build:
            dockerfile: ./docker/php/Dockerfile
            context: .
        working_dir: /srv/
        volumes:
            - ./:/srv
        links:
            - database
            - mailer

    mailer:
        build: ./docker/mailcatcher/

    node:
        build: ./docker/node/
        working_dir: /srv/
        volumes:
            - ./:/srv
        command: 'sleep 99999d'

    # Dump can be saved in var/ that's why it's the only directory we share
    database:
        image: 'mysql:5.7'
        working_dir: /srv/
        volumes:
            - ./var/:/srv/:ro
            - ./docker/mysql/etc/bind.cnf:/etc/mysql/conf.d/bind.cnf
            - ./docker/mysql/etc/docker-override.cnf:/etc/mysql/conf.d/docker.cnf
            - db_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_HOST: 0.0.0.0
            MYSQL_ROOT_HOST: "%"
