version: "3.4"

volumes:
    db_data:
    php_socket:

services:
    php:
        build:
            context: ./docker/php/
        working_dir: /srv/
        volumes:
            - "./:/srv"
            - "php_socket:/var/run/php"

    caddy:
        build:
            context: ./docker/caddy/
        working_dir: /srv/
        volumes:
            - "php_socket:/var/run/php"
            - "./:/srv/"
        ports:
            - "80:80"
            - "443:443"
            - "443:443/udp"

    mailer:
        image: mailhog/mailhog

    node:
        build: ./docker/node/
        working_dir: /srv/
        volumes:
            - "./:/srv"
        command: 'sleep 99999d'

    database:
        image: 'mysql:5.7'
        working_dir: /srv/
        volumes:
            - ./data/:/srv/:ro
            - ./docker/mysql/etc/bind.cnf:/etc/mysql/conf.d/bind.cnf
            - ./docker/mysql/etc/docker-override.cnf:/etc/mysql/conf.d/docker.cnf
            - db_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_HOST: 0.0.0.0
            MYSQL_ROOT_HOST: "%"
