
# A simple route used to manage and edit the template
_materialize_theme:
    path:     /_theme
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    _theme/materialize.html.twig

_email_contact:
    path:     /_email/contact
    controller: Main\Controller\Dev\EmailTemplateController
