easy_admin:
    entities:

        Ogham:
            label: admin.corahn_rin.ogham
            class: CorahnRin\Entity\Ogham
            controller: Admin\CustomController\CorahnRin\AdminOghamController
            list:
                fields:
                    - { property: id, label: 'admin.entities.common.id' }
                    - { property: name, label: 'admin.entities.common.name' }
                    - { property: description, label: 'admin.entities.common.description' }
                    - { property: book, label: 'admin.entities.common.book' }

            form:
                fields:
                    - { property: name, label: 'admin.entities.common.name' }
                    - { property: description, label: 'admin.entities.common.description' }
                    - property: type
                      label: 'admin.entities.common.type'
                      type: choice
                      type_options:
                          choices: !php/const CorahnRin\Data\OghamType::ALL
                    - { property: book, label: 'admin.entities.common.book' }
