<?php

declare(strict_types=1);

/*
 * This file is part of the Corahn-Rin package.
 *
 * (c) Alexandre Rock Ancelet <pierstoval@gmail.com> and Studio Agate.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace DataFixtures\CorahnRin;

use CorahnRin\Entity\GameInvitation;
use DataFixtures\UsersFixtures;
use Doctrine\Bundle\FixturesBundle\ORMFixtureInterface;
use Doctrine\Common\DataFixtures\DependentFixtureInterface;
use Orbitale\Component\ArrayFixture\ArrayFixture;

class GamesInvitationsFixtures extends ArrayFixture implements ORMFixtureInterface, DependentFixtureInterface
{
    // Generated by the TokenGenerator class
    public const DEFAULT_INVITATION_TOKEN = 'YF5QviK9WZRCneeInBmFxLHw8eT1whQLym9d-M4tKTQ';

    public function getEntityClass(): string
    {
        return GameInvitation::class;
    }

    public function getObjects(): iterable
    {
        return [
            [
                'game' => $this->getReference('corahnrin-game-'.GamesFixtures::ID_WITH_INVITATIONS),
                'character' => $this->getReference('corahnrin-character-invited-character'),
                'token' => self::DEFAULT_INVITATION_TOKEN,
            ],
        ];
    }

    public function getDependencies()
    {
        return [
            GamesFixtures::class,
            CharactersFixtures::class,
            UsersFixtures::class,
        ];
    }
}
