<?php

declare(strict_types=1);

/*
 * This file is part of the Corahn-Rin package.
 *
 * (c) Alexandre Rock Ancelet <pierstoval@gmail.com> and Studio Agate.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace DataFixtures\CorahnRin;

use CorahnRin\Data\Ways;
use CorahnRin\Document\PersonalityTrait;
use Doctrine\Bundle\FixturesBundle\ORMFixtureInterface;
use Doctrine\Common\DataFixtures\DependentFixtureInterface;
use Orbitale\Component\ArrayFixture\ArrayFixture;

class TraitsFixtures extends ArrayFixture implements ORMFixtureInterface, DependentFixtureInterface
{
    public const ID_THOUGHTFUL = 56;
    public const ID_WEAK_CHARACTER = 19;

    public function getEntityClass(): string
    {
        return PersonalityTrait::class;
    }

    public function getObjects(): iterable
    {
        $book = $this->getReference('corahnrin-book-2');

        $way1 = Ways::COMBATIVENESS;
        $way2 = Ways::CREATIVITY;
        $way3 = Ways::EMPATHY;
        $way4 = Ways::REASON;
        $way5 = Ways::CONVICTION;

        return [
            [
                'id' => 1,
                'way' => $way1,
                'name' => 'Combatif',
                'nameFemale' => 'Combative',
                'isQuality' => 1,
                'major' => 1,
                'book' => $book,
            ],
            [
                'id' => 2,
                'way' => $way1,
                'name' => 'Optimiste',
                'nameFemale' => 'Optimiste',
                'isQuality' => 1,
                'major' => 1,
                'book' => $book,
            ],
            [
                'id' => 3,
                'way' => $way1,
                'name' => 'Dynamique',
                'nameFemale' => 'Dynamique',
                'isQuality' => 1,
                'major' => 1,
                'book' => $book,
            ],
            [
                'id' => 4,
                'way' => $way1,
                'name' => 'Courageux',
                'nameFemale' => 'Courageuse',
                'isQuality' => 1,
                'major' => 1,
                'book' => $book,
            ],
            [
                'id' => 5,
                'way' => $way1,
                'name' => 'Pugnace',
                'nameFemale' => 'Pugnace',
                'isQuality' => 1,
                'major' => 1,
                'book' => $book,
            ],
            [
                'id' => 6,
                'way' => $way1,
                'name' => 'Calme',
                'nameFemale' => 'Calme',
                'isQuality' => 1,
                'major' => 0,
                'book' => $book,
            ],
            [
                'id' => 7,
                'way' => $way1,
                'name' => 'Flegmatique',
                'nameFemale' => 'Flegmatique',
                'isQuality' => 1,
                'major' => 0,
                'book' => $book,
            ],
            [
                'id' => 8,
                'way' => $way1,
                'name' => 'Paisible',
                'nameFemale' => 'Paisible',
                'isQuality' => 1,
                'major' => 0,
                'book' => $book,
            ],
            [
                'id' => 9,
                'way' => $way1,
                'name' => 'Pondéré',
                'nameFemale' => 'Pondérée',
                'isQuality' => 1,
                'major' => 0,
                'book' => $book,
            ],
            [
                'id' => 10,
                'way' => $way1,
                'name' => 'Impulsif',
                'nameFemale' => 'Impulsive',
                'isQuality' => 0,
                'major' => 1,
                'book' => $book,
            ],
            [
                'id' => 11,
                'way' => $way1,
                'name' => 'Outrecuidant',
                'nameFemale' => 'Outrecuidante',
                'isQuality' => 0,
                'major' => 1,
                'book' => $book,
            ],
            [
                'id' => 12,
                'way' => $way1,
                'name' => 'Fier',
                'nameFemale' => 'Fière',
                'isQuality' => 0,
                'major' => 1,
                'book' => $book,
            ],
            [
                'id' => 13,
                'way' => $way1,
                'name' => 'Buté',
                'nameFemale' => 'Butée',
                'isQuality' => 0,
                'major' => 1,
                'book' => $book,
            ],
            [
                'id' => 14,
                'way' => $way1,
                'name' => 'Orgueilleux',
                'nameFemale' => 'Orgueilleuse',
                'isQuality' => 0,
                'major' => 1,
                'book' => $book,
            ],
            [
                'id' => 15,
                'way' => $way1,
                'name' => 'Vaniteux',
                'nameFemale' => 'Vaniteuse',
                'isQuality' => 0,
                'major' => 1,
                'book' => $book,
            ],
            [
                'id' => 16,
                'way' => $way1,
                'name' => 'Pessimiste',
                'nameFemale' => 'Pessimiste',
                'isQuality' => 0,
                'major' => 0,
                'book' => $book,
            ],
            [
                'id' => 17,
                'way' => $way1,
                'name' => 'Mou',
                'nameFemale' => 'Molle',
                'isQuality' => 0,
                'major' => 0,
                'book' => $book,
            ],
            [
                'id' => 18,
                'way' => $way1,
                'name' => 'Triste',
                'nameFemale' => 'Triste',
                'isQuality' => 0,
                'major' => 0,
                'book' => $book,
            ],
            [
                'id' => self::ID_WEAK_CHARACTER,
                'way' => $way1,
                'name' => 'Faible caractère',
                'nameFemale' => 'Faible caractère',
                'isQuality' => 0,
                'major' => 0,
                'book' => $book,
            ],
            [
                'id' => 20,
                'way' => $way1,
                'name' => 'Peureux',
                'nameFemale' => 'Peureuse',
                'isQuality' => 0,
                'major' => 0,
                'book' => $book,
            ],
            [
                'id' => 21,
                'way' => $way1,
                'name' => 'Mauvaise estime',
                'nameFemale' => 'Mauvaise estime',
                'isQuality' => 0,
                'major' => 0,
                'book' => $book,
            ],
            [
                'id' => 22,
                'way' => $way1,
                'name' => 'Lâche',
                'nameFemale' => 'Lâche',
                'isQuality' => 0,
                'major' => 0,
                'book' => $book,
            ],
            [
                'id' => 23,
                'way' => $way2,
                'name' => 'Inventif',
                'nameFemale' => 'Inventive',
                'isQuality' => 1,
                'major' => 1,
                'book' => $book,
            ],
            [
                'id' => 24,
                'way' => $way2,
                'name' => 'Original',
                'nameFemale' => 'Originale',
                'isQuality' => 1,
                'major' => 1,
                'book' => $book,
            ],
            [
                'id' => 25,
                'way' => $way2,
                'name' => 'Débrouillard',
                'nameFemale' => 'Débrouillarde',
                'isQuality' => 1,
                'major' => 1,
                'book' => $book,
            ],
            [
                'id' => 26,
                'way' => $way2,
                'name' => 'Drôle',
                'nameFemale' => 'Drôle',
                'isQuality' => 1,
                'major' => 1,
                'book' => $book,
            ],
            [
                'id' => 27,
                'way' => $way2,
                'name' => 'Poète',
                'nameFemale' => 'Poète',
                'isQuality' => 1,
                'major' => 1,
                'book' => $book,
            ],
            [
                'id' => 28,
                'way' => $way2,
                'name' => 'Sérieux',
                'nameFemale' => 'Sérieuse',
                'isQuality' => 1,
                'major' => 0,
                'book' => $book,
            ],
            [
                'id' => 29,
                'way' => $way2,
                'name' => 'Traditionaliste',
                'nameFemale' => 'Traditionaliste',
                'isQuality' => 1,
                'major' => 0,
                'book' => $book,
            ],
            [
                'id' => 30,
                'way' => $way2,
                'name' => 'Procédurier',
                'nameFemale' => 'Procédurière',
                'isQuality' => 1,
                'major' => 0,
                'book' => $book,
            ],
            [
                'id' => 31,
                'way' => $way2,
                'name' => 'Discipliné',
                'nameFemale' => 'Disciplinée',
                'isQuality' => 1,
                'major' => 0,
                'book' => $book,
            ],
            [
                'id' => 32,
                'way' => $way2,
                'name' => 'Anticonformiste',
                'nameFemale' => 'Anticonformiste',
                'isQuality' => 0,
                'major' => 1,
                'book' => $book,
            ],
            [
                'id' => 33,
                'way' => $way2,
                'name' => 'Rebelle',
                'nameFemale' => 'Rebelle',
                'isQuality' => 0,
                'major' => 1,
                'book' => $book,
            ],
            [
                'id' => 34,
                'way' => $way2,
                'name' => 'Indiscipliné',
                'nameFemale' => 'Indisciplinée',
                'isQuality' => 0,
                'major' => 1,
                'book' => $book,
            ],
            [
                'id' => 35,
                'way' => $way2,
                'name' => 'Excentrique',
                'nameFemale' => 'Excentrique',
                'isQuality' => 0,
                'major' => 1,
                'book' => $book,
            ],
            [
                'id' => 36,
                'way' => $way2,
                'name' => 'Menteur',
                'nameFemale' => 'Menteuse',
                'isQuality' => 0,
                'major' => 1,
                'book' => $book,
            ],
            [
                'id' => 37,
                'way' => $way2,
                'name' => 'Empoté',
                'nameFemale' => 'Empotée',
                'isQuality' => 0,
                'major' => 0,
                'book' => $book,
            ],
            [
                'id' => 38,
                'way' => $way2,
                'name' => 'Esprit étriqué',
                'nameFemale' => 'Esprit étriqué',
                'isQuality' => 0,
                'major' => 0,
                'book' => $book,
            ],
            [
                'id' => 39,
                'way' => $way2,
                'name' => 'Ascétique',
                'nameFemale' => 'Ascétique',
                'isQuality' => 0,
                'major' => 0,
                'book' => $book,
            ],
            [
                'id' => 40,
                'way' => $way2,
                'name' => 'Rigide',
                'nameFemale' => 'Rigide',
                'isQuality' => 0,
                'major' => 0,
                'book' => $book,
            ],
            [
                'id' => 41,
                'way' => $way3,
                'name' => 'Réceptif',
                'nameFemale' => 'Réceptive',
                'isQuality' => 1,
                'major' => 1,
                'book' => $book,
            ],
            [
                'id' => 42,
                'way' => $way3,
                'name' => 'Sensible',
                'nameFemale' => 'Sensible',
                'isQuality' => 1,
                'major' => 1,
                'book' => $book,
            ],
            [
                'id' => 43,
                'way' => $way3,
                'name' => 'Intuitif',
                'nameFemale' => 'Intuitive',
                'isQuality' => 1,
                'major' => 1,
                'book' => $book,
            ],
            [
                'id' => 44,
                'way' => $way3,
                'name' => 'Extraverti',
                'nameFemale' => 'Extravertie',
                'isQuality' => 1,
                'major' => 1,
                'book' => $book,
            ],
            [
                'id' => 45,
                'way' => $way3,
                'name' => 'Contrôle de ses émotions',
                'nameFemale' => 'Contrôle de ses émotions',
                'isQuality' => 1,
                'major' => 0,
                'book' => $book,
            ],
            [
                'id' => 46,
                'way' => $way3,
                'name' => 'Peu influençable',
                'nameFemale' => 'Peu influençable',
                'isQuality' => 1,
                'major' => 0,
                'book' => $book,
            ],
            [
                'id' => 47,
                'way' => $way3,
                'name' => 'Émotif',
                'nameFemale' => 'Émotive',
                'isQuality' => 0,
                'major' => 1,
                'book' => $book,
            ],
            [
                'id' => 48,
                'way' => $way3,
                'name' => 'Influençable',
                'nameFemale' => 'Influençable',
                'isQuality' => 0,
                'major' => 1,
                'book' => $book,
            ],
            [
                'id' => 49,
                'way' => $way3,
                'name' => 'Bavard',
                'nameFemale' => 'Bavarde',
                'isQuality' => 0,
                'major' => 1,
                'book' => $book,
            ],
            [
                'id' => 50,
                'way' => $way3,
                'name' => 'Austère',
                'nameFemale' => 'Austère',
                'isQuality' => 0,
                'major' => 0,
                'book' => $book,
            ],
            [
                'id' => 51,
                'way' => $way3,
                'name' => 'Insensible',
                'nameFemale' => 'Insensible',
                'isQuality' => 0,
                'major' => 0,
                'book' => $book,
            ],
            [
                'id' => 52,
                'way' => $way3,
                'name' => 'Renfermé',
                'nameFemale' => 'Renfermée',
                'isQuality' => 0,
                'major' => 0,
                'book' => $book,
            ],
            [
                'id' => 53,
                'way' => $way3,
                'name' => 'Taciturne',
                'nameFemale' => 'Taciturne',
                'isQuality' => 0,
                'major' => 0,
                'book' => $book,
            ],
            [
                'id' => 54,
                'way' => $way3,
                'name' => 'Froid',
                'nameFemale' => 'Froide',
                'isQuality' => 0,
                'major' => 0,
                'book' => $book,
            ],
            [
                'id' => 55,
                'way' => $way3,
                'name' => 'Individualiste',
                'nameFemale' => 'Individualiste',
                'isQuality' => 0,
                'major' => 0,
                'book' => $book,
            ],
            [
                'id' => self::ID_THOUGHTFUL,
                'way' => $way4,
                'name' => 'Réfléchi',
                'nameFemale' => 'Réfléchie',
                'isQuality' => 1,
                'major' => 1,
                'book' => $book,
            ],
            [
                'id' => 57,
                'way' => $way4,
                'name' => 'Ingénieux',
                'nameFemale' => 'Ingénieuse',
                'isQuality' => 1,
                'major' => 1,
                'book' => $book,
            ],
            [
                'id' => 58,
                'way' => $way4,
                'name' => 'Prudent',
                'nameFemale' => 'Prudente',
                'isQuality' => 1,
                'major' => 1,
                'book' => $book,
            ],
            [
                'id' => 59,
                'way' => $way4,
                'name' => 'Logique',
                'nameFemale' => 'Logique',
                'isQuality' => 1,
                'major' => 1,
                'book' => $book,
            ],
            [
                'id' => 60,
                'way' => $way4,
                'name' => 'Concentré',
                'nameFemale' => 'Concentrée',
                'isQuality' => 1,
                'major' => 1,
                'book' => $book,
            ],
            [
                'id' => 61,
                'way' => $way4,
                'name' => 'Spontané',
                'nameFemale' => 'Spontanée',
                'isQuality' => 1,
                'major' => 0,
                'book' => $book,
            ],
            [
                'id' => 62,
                'way' => $way4,
                'name' => 'Téméraire',
                'nameFemale' => 'Téméraire',
                'isQuality' => 1,
                'major' => 0,
                'book' => $book,
            ],
            [
                'id' => 63,
                'way' => $way4,
                'name' => 'Peu entravé',
                'nameFemale' => 'Peu entravée',
                'isQuality' => 1,
                'major' => 0,
                'book' => $book,
            ],
            [
                'id' => 64,
                'way' => $way4,
                'name' => 'Abstraction',
                'nameFemale' => 'Abstraction',
                'isQuality' => 0,
                'major' => 1,
                'book' => $book,
            ],
            [
                'id' => 65,
                'way' => $way4,
                'name' => 'Replié sur soi',
                'nameFemale' => 'Repliée sur soi',
                'isQuality' => 0,
                'major' => 1,
                'book' => $book,
            ],
            [
                'id' => 66,
                'way' => $way4,
                'name' => 'Précautionneux',
                'nameFemale' => 'Précautionneuse',
                'isQuality' => 0,
                'major' => 1,
                'book' => $book,
            ],
            [
                'id' => 67,
                'way' => $way4,
                'name' => 'Hésitant',
                'nameFemale' => 'Hésitante',
                'isQuality' => 0,
                'major' => 1,
                'book' => $book,
            ],
            [
                'id' => 68,
                'way' => $way4,
                'name' => 'Distrait',
                'nameFemale' => 'Distraite',
                'isQuality' => 0,
                'major' => 0,
                'book' => $book,
            ],
            [
                'id' => 69,
                'way' => $way4,
                'name' => 'Imprudent',
                'nameFemale' => 'Imprudente',
                'isQuality' => 0,
                'major' => 0,
                'book' => $book,
            ],
            [
                'id' => 70,
                'way' => $way4,
                'name' => 'Irréfléchi',
                'nameFemale' => 'Irréfléchie',
                'isQuality' => 0,
                'major' => 0,
                'book' => $book,
            ],
            [
                'id' => 71,
                'way' => $way5,
                'name' => 'Droit',
                'nameFemale' => 'Droite',
                'isQuality' => 1,
                'major' => 1,
                'book' => $book,
            ],
            [
                'id' => 72,
                'way' => $way5,
                'name' => 'Persévérant',
                'nameFemale' => 'Persévérante',
                'isQuality' => 1,
                'major' => 1,
                'book' => $book,
            ],
            [
                'id' => 73,
                'way' => $way5,
                'name' => 'Loyal',
                'nameFemale' => 'Loyale',
                'isQuality' => 1,
                'major' => 1,
                'book' => $book,
            ],
            [
                'id' => 74,
                'way' => $way5,
                'name' => 'Incorruptible',
                'nameFemale' => 'Incorruptible',
                'isQuality' => 1,
                'major' => 1,
                'book' => $book,
            ],
            [
                'id' => 75,
                'way' => $way5,
                'name' => 'Généreux',
                'nameFemale' => 'Généreuse',
                'isQuality' => 1,
                'major' => 1,
                'book' => $book,
            ],
            [
                'id' => 76,
                'way' => $way5,
                'name' => 'Libre',
                'nameFemale' => 'Libre',
                'isQuality' => 1,
                'major' => 0,
                'book' => $book,
            ],
            [
                'id' => 77,
                'way' => $way5,
                'name' => 'Indépendant',
                'nameFemale' => 'Indépendante',
                'isQuality' => 1,
                'major' => 0,
                'book' => $book,
            ],
            [
                'id' => 78,
                'way' => $way5,
                'name' => 'Rigide',
                'nameFemale' => 'Rigide',
                'isQuality' => 0,
                'major' => 1,
                'book' => $book,
            ],
            [
                'id' => 79,
                'way' => $way5,
                'name' => 'Intolérant',
                'nameFemale' => 'Intolérante',
                'isQuality' => 0,
                'major' => 1,
                'book' => $book,
            ],
            [
                'id' => 80,
                'way' => $way5,
                'name' => 'Fanatique',
                'nameFemale' => 'Fanatique',
                'isQuality' => 0,
                'major' => 1,
                'book' => $book,
            ],
            [
                'id' => 81,
                'way' => $way5,
                'name' => 'Influençable',
                'nameFemale' => 'Influençable',
                'isQuality' => 0,
                'major' => 1,
                'book' => $book,
            ],
            [
                'id' => 82,
                'way' => $way5,
                'name' => 'Capricieux',
                'nameFemale' => 'Capricieuse',
                'isQuality' => 0,
                'major' => 0,
                'book' => $book,
            ],
            [
                'id' => 83,
                'way' => $way5,
                'name' => 'Inconstant',
                'nameFemale' => 'Inconstante',
                'isQuality' => 0,
                'major' => 0,
                'book' => $book,
            ],
            [
                'id' => 84,
                'way' => $way5,
                'name' => 'Inconséquent',
                'nameFemale' => 'Inconséquente',
                'isQuality' => 0,
                'major' => 0,
                'book' => $book,
            ],
            [
                'id' => 85,
                'way' => $way5,
                'name' => 'Immoral',
                'nameFemale' => 'Immorale',
                'isQuality' => 0,
                'major' => 0,
                'book' => $book,
            ],
            [
                'id' => 86,
                'way' => $way5,
                'name' => 'Doute',
                'nameFemale' => 'Doute',
                'isQuality' => 0,
                'major' => 0,
                'book' => $book,
            ],
            [
                'id' => 87,
                'way' => $way5,
                'name' => 'Traître',
                'nameFemale' => 'Traitresse',
                'isQuality' => 0,
                'major' => 0,
                'book' => $book,
            ],
            [
                'id' => 88,
                'way' => $way2,
                'name' => 'Opportuniste',
                'nameFemale' => 'Opportuniste',
                'isQuality' => 0,
                'major' => 0,
                'book' => $book,
            ],
            [
                'id' => 89,
                'way' => $way1,
                'name' => 'Téméraire',
                'nameFemale' => 'Téméraire',
                'isQuality' => 0,
                'major' => 1,
                'book' => $book,
            ],
            [
                'id' => 90,
                'way' => $way1,
                'name' => 'Persévérant',
                'nameFemale' => 'Persévérante',
                'isQuality' => 1,
                'major' => 1,
                'book' => $book,
            ],
            [
                'id' => 91,
                'way' => $way5,
                'name' => 'Peu fiable',
                'nameFemale' => 'Peu fiable',
                'isQuality' => 0,
                'major' => 0,
                'book' => $book,
            ],
            [
                'id' => 92,
                'way' => $way2,
                'name' => 'Austère',
                'nameFemale' => 'Austère',
                'isQuality' => 0,
                'major' => 0,
                'book' => $book,
            ],
            [
                'id' => 93,
                'way' => $way4,
                'name' => 'Austère',
                'nameFemale' => 'Austère',
                'isQuality' => 0,
                'major' => 1,
                'book' => $book,
            ],
            [
                'id' => 94,
                'way' => $way1,
                'name' => 'Distrait',
                'nameFemale' => 'Distraite',
                'isQuality' => 0,
                'major' => 0,
                'book' => $book,
            ],
        ];
    }

    public function getDependencies()
    {
        return [
            BooksFixtures::class,
        ];
    }

    protected function getReferencePrefix(): ?string
    {
        return 'corahnrin-traits-';
    }
}
